In [243]:
import numpy as np
import pandas as pd
import random
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

matrix = np.loadtxt('matrix.txt')
matrix = matrix.astype(int)
print(matrix)


[[ 0 -1  4 -1 -1 -1 -1 -1  3  1 -1  2 -1  5 -1 -1]
 [ 4  0 -1 -1  1 -1  5 -1 -1 -1  2 -1 -1 -1  3 -1]
 [-1 -1  0  4  2 -1 -1 -1 -1  3 -1  5 -1  1 -1 -1]
 [-1  3  2  0 -1 -1 -1 -1  1  4 -1 -1 -1 -1  5 -1]
 [ 3 -1 -1 -1  0 -1 -1 -1 -1  2 -1  1 -1  4 -1  5]
 [ 5 -1 -1 -1 -1  0 -1  1  4 -1  3 -1 -1 -1 -1 -1]
 [-1 -1 -1  5 -1  4  0 -1 -1 -1 -1  3  2 -1 -1  1]
 [ 1 -1 -1 -1  5 -1 -1  0  2 -1 -1 -1  4 -1 -1  3]
 [-1 -1  1 -1  3 -1 -1  4  0 -1  5 -1 -1 -1 -1  2]
 [-1  2  5 -1 -1 -1  1 -1 -1  0 -1  4 -1  3 -1 -1]
 [-1  5 -1  3  4 -1  2 -1 -1 -1  0 -1 -1 -1 -1 -1]
 [-1  4 -1  1 -1 -1 -1  3  5 -1 -1  0 -1  2 -1 -1]
 [-1  1 -1 -1 -1  3 -1  2 -1  5 -1 -1  0 -1  4 -1]
 [-1 -1 -1  2 -1  1  3 -1 -1 -1  4 -1  5  0 -1 -1]
 [-1 -1 -1 -1 -1  5 -1 -1 -1 -1 -1 -1  3 -1  0  4]
 [ 2 -1  3 -1 -1 -1  4  5 -1 -1 -1 -1  1 -1 -1  0]]


In [244]:
h, w = matrix.shape
possible_partners = [[] for _ in range(h)]
for i in range(h):
    inner_list = []
    for j in range(w):
        if matrix[i][j] == -1:
            inner_list.append(j)
    possible_partners[i] = inner_list

# Choose a partner that a person hasn't had before
def choose_partner(possible_partners, gifter):
    partner = random.choice(possible_partners[gifter])
    return partner

# Check to see if that person has already been used
def is_valid(matrix, reciever, year, tried):
    for i in range(0,16):
        if reciever in tried[i]:
            return False
        if matrix.T[reciever][i] == year:
            return False
        
    return True


In [253]:
tried = [[] for _ in range(h)]

def assign_partners(matrix, possible_partners, year, tried, index=0):
    if index == len(matrix):
        return True  # All partners have been assigned
    random.shuffle(possible_partners[index])
    for reciever in possible_partners[index]:
        if is_valid(matrix, reciever, year, tried):
            matrix[index][reciever] = year
            tried[index].append(reciever)
            possible_partners[index].remove(reciever)

            if assign_partners(matrix, possible_partners, year, tried, index + 1):
                return True  # Recurse

            matrix[index][reciever] = -1  # Undo assignment
            tried[index].remove(reciever)  # Undo assignment
            possible_partners[index].append(reciever)

    return False
index = 0
remaining_years = [i for i in range(6,16)]
for year in remaining_years:
    assign_partners(matrix, possible_partners, year, tried, index)

print(matrix)

[[ 0  9  4 14 13 12  7 11  3  1  8  2  6  5 10 -1]
 [ 4  0 12  9  1 13  5 -1 10  7  2  8 14 11  3  6]
 [ 9  8  0  4  2  7 11 14 12  3  6  5 -1  1 13 10]
 [14  3  2  0 -1  6  8  9  1  4 11 12 10  7  5 13]
 [ 3 12  8  7  0  9 -1 13 14  2 10  1 11  4  6  5]
 [ 5 -1 10  8 12  0  9  1  4  6  3 -1 13 14  7 11]
 [11 14  6  5 10  4  0 12  7  8 13  3  2  9 -1  1]
 [ 1  6  7 11  5 -1 13  0  2 10  9 14  4  8 12  3]
 [ 7 13  1 12  3 10 14  4  0  9  5  6  8 -1 11  2]
 [10  2  5 13  9 11  1  6  8  0 -1  4 12  3 14  7]
 [ 6  5 13  3  4  8  2 10 11 -1  0  7  9 12 -1 14]
 [13  4  9  1  6 14 10  3  5 11 12  0  7  2 -1  8]
 [ 8  1 11  6  7  3 12  2 -1  5 14 10  0 13  4  9]
 [-1 10 14  2  8  1  3  7  6 13  4 11  5  0  9 12]
 [12  7 -1 -1 11  5  6  8  9 14 -1 13  3 10  0  4]
 [ 2 11  3 10 14 -1  4  5 13 12  7  9  1  6  8  0]]


In [254]:
print(possible_partners)

[[15], [7], [12], [4], [6], [1, 11], [14], [5], [13], [10], [14, 9], [14], [8], [0], [10, 3, 2], [5]]


In [221]:
# Run this cell to save the current matrix to a text file 
# to use for the next year

np.savetxt('matrix_year_6.txt', matrix, fmt='%d')

In [255]:
name_dictionary = {0:"Logan", 1:"Matt", 2:"Jake", 3:"Kyle", 4:"Manny", 5:"Brett", 6:"Garrett", 7:"Steve", 8:"Nicky",
                  9:"Joel", 10:"Nico", 11:"Will", 12:"Paul", 13:"Riley", 14:"Ben", 15:"Samie"}
email_dictionary = {0:"#", 1:"#", 2:"#", 3:"#",
                   4:"#", 5:"#", 6:"#",
                   7:"#", 8:"#", 9:"#", 10:"#",
                   11:"#", 12:"#", 13:"#", 14:"#",
                   15:"#"}

password = "####"
msg['From'] = "#"
server = smtplib.SMTP('smtp.gmail.com',587)
server.starttls()
server.login(msg['From'], password)

current_year = 6
 Put this in for loop to send all emails
 for i in range(0,16):
     for j in range(0,16):
         if matrix[i][j] == current_year:
             msg = MIMEMultipart()
             msg['To'] = email_dictionary[i]
             msg['Subject'] = "Secret Santa"
             person = name_dictionary[j]
             message = f"You have {person} for secret santa"
             msg.attach(MIMEText(message, 'plain'))
             server.sendmail(msg['From'], msg['To'], msg.as_string())
 server.quit()
            
            


KeyError: 13